<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFMhwhxV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFMhwhxV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFMhwhxV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFMhwhxV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFMhwhxV\App_KernelDevDebugContainer([
    'container.build_hash' => 'FMhwhxV',
    'container.build_id' => '921e99ce',
    'container.build_time' => 1669306387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFMhwhxV');
