<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJC2CxkI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJC2CxkI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJC2CxkI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJC2CxkI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJC2CxkI\App_KernelDevDebugContainer([
    'container.build_hash' => 'JC2CxkI',
    'container.build_id' => '8a6cceec',
    'container.build_time' => 1669643761,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJC2CxkI');
